name: Publish Docker image
on:
  push:
    branches: [main]

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        include:
          - dockerfile: ./5.9/ubuntu/18.04/Dockerfile
            platforms: 'linux/amd64'
            tags:
              - ghcr.io/swiftwasm/swift:5.9-bionic
              - ghcr.io/swiftwasm/swift:bionic
          - dockerfile: ./5.9/ubuntu/20.04/Dockerfile
            platforms: 'linux/amd64,linux/arm64'
            tags:
              - ghcr.io/swiftwasm/swift:5.9-focal
              - ghcr.io/swiftwasm/swift:focal
          - dockerfile: ./5.9/ubuntu/22.04/Dockerfile
            platforms: 'linux/amd64'
            tags:
              - ghcr.io/swiftwasm/swift:5.9-jammy
              - ghcr.io/swiftwasm/swift:jammy
              - ghcr.io/swiftwasm/swift:5.9
              - ghcr.io/swiftwasm/swift:latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - uses: docker/setup-qemu-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.SWIFTWASM_PERSONAL_TOKEN }}
      - name: Push ${{ matrix.dockerfile }}
        uses: docker/build-push-action@v3
        with:
          platforms: ${{ matrix.platforms }}
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ join(matrix.tags, ',') }}
